import { useEffect, useRef, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View } from 'react-native';
import { BackButton, PrimaryButton, Screen, TempleMark } from '../components/ui';
import { colors } from '../theme/theme';

export function OtpVerificationScreen({ phone, onBack, onVerify }: { phone: string; onBack: () => void; onVerify: (code: string) => void }) {
  const [code, setCode] = useState(''); const [seconds, setSeconds] = useState(42); const input = useRef<TextInput>(null);
  useEffect(() => { const timer = setInterval(() => setSeconds((old) => Math.max(0, old - 1)), 1000); return () => clearInterval(timer); }, []);
  const resend = () => { setSeconds(42); setCode(''); Alert.alert('OTP resent', 'A new demo code has been sent to your mobile number.'); };
  return <Screen scroll><BackButton onPress={onBack} /><View style={styles.header}><View style={styles.aura} /><TempleMark /><Text style={styles.title}>Verify OTP</Text><Text style={styles.copy}>Enter the 4-digit code sent to{`\n`}<Text style={styles.phone}>+91 {phone || '98765 43210'}</Text></Text></View><View style={styles.card}><View style={styles.cardHead}><Text style={styles.token}>AUTHENTICATION TOKEN</Text><Text style={styles.valid}>Valid for 5 mins</Text></View><TextInput ref={input} value={code} onChangeText={(value) => setCode(value.replace(/\D/g, '').slice(0, 4))} keyboardType="number-pad" maxLength={4} style={styles.hiddenInput} autoFocus /><View style={styles.boxes}>{Array.from({ length: 4 }, (_, index) => <View key={index} style={[styles.box, index === code.length && code.length < 4 && styles.activeBox]}><Text style={styles.digit}>{code[index] || '•'}</Text></View>)}</View><View style={styles.resendRow}><Text style={styles.resendCopy}>Didn't receive code?</Text><Text onPress={resend} style={styles.resend}> Resend OTP</Text><Text style={styles.timer}> 00:{String(seconds).padStart(2, '0')}s</Text></View><PrimaryButton label="Verify & Continue" disabled={code.length !== 4} onPress={() => onVerify(code)} /></View><View style={styles.trust}><Text style={styles.trustTitle}>Sangh Trusted Verification</Text><Text style={styles.trustCopy}>End-to-end verification with your local Jain Sangh registry for authentic darshan access.</Text></View><View style={styles.quote}><Text style={styles.quoteText}>“Parasparopagraho Jīvānām”</Text><Text style={styles.quoteSub}>SOULS RENDER SERVICE TO ONE ANOTHER</Text></View></Screen>;
}
const styles = StyleSheet.create({ header: { alignItems: 'center', marginTop: 18, marginBottom: 22 }, aura: { width: 110, height: 110, borderRadius: 55, backgroundColor: colors.goldLight, opacity: .35, position: 'absolute', top: -13 }, title: { color: colors.maroon, fontFamily: 'serif', fontSize: 31, fontWeight: '600', marginTop: 16 }, copy: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 7 }, phone: { color: colors.ink, fontWeight: '700' }, card: { backgroundColor: colors.white, borderRadius: 16, padding: 17, shadowColor: colors.ink, shadowOpacity: .06, shadowRadius: 9, elevation: 2 }, cardHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 13 }, token: { color: colors.muted, fontSize: 9, letterSpacing: 1, fontWeight: '700' }, valid: { color: colors.gold, fontSize: 10, fontWeight: '700' }, hiddenInput: { position: 'absolute', opacity: 0, width: 1, height: 1 }, boxes: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 17 }, box: { width: 43, height: 54, borderRadius: 9, backgroundColor: colors.surfaceLow, alignItems: 'center', justifyContent: 'center' }, activeBox: { borderWidth: 1.5, borderColor: colors.gold, backgroundColor: colors.white }, digit: { color: colors.maroon, fontSize: 22, fontWeight: '700' }, resendRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', backgroundColor: colors.surfaceLow, borderRadius: 10, padding: 10, marginBottom: 17 }, resendCopy: { color: colors.muted, fontSize: 11 }, resend: { color: colors.maroon, fontSize: 11, fontWeight: '700', textDecorationLine: 'underline' }, timer: { color: colors.gold, fontSize: 11, fontWeight: '700', marginLeft: 'auto' }, trust: { backgroundColor: colors.surfaceLow, borderRadius: 13, padding: 15, marginTop: 20 }, trustTitle: { color: colors.ink, fontWeight: '700', fontSize: 13 }, trustCopy: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 4 }, quote: { alignItems: 'center', marginTop: 27, marginBottom: 15 }, quoteText: { color: colors.gold, fontFamily: 'serif', fontStyle: 'italic', fontSize: 17 }, quoteSub: { color: colors.outline, fontSize: 8, letterSpacing: 1, marginTop: 5 } });
