import { useState } from 'react';
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { BackButton, PrimaryButton, Screen, TempleMark } from '../components/ui';
import { colors } from '../theme/theme';

const formatPhone = (value: string) => { const digits = value.replace(/\D/g, '').slice(0, 10); return digits.length > 5 ? `${digits.slice(0, 5)} ${digits.slice(5)}` : digits; };
export function PhoneLoginScreen({ onBack, onContinue }: { onBack: () => void; onContinue: (phone: string) => void }) {
  const [phone, setPhone] = useState(''); const valid = phone.replace(/\s/g, '').length === 10;
  return <Screen scroll><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.content}><BackButton onPress={onBack} /><View style={styles.header}><View style={styles.aura} /><TempleMark /><Text style={styles.eyebrow}>SANGH MEMBER ACCESS</Text><Text style={styles.title}>Welcome back</Text><Text style={styles.copy}>Enter your mobile number to receive a secure verification code.</Text></View><View><Text style={styles.label}>Mobile Number</Text><View style={styles.phoneRow}><Text style={styles.prefix}>🇮🇳  +91</Text><TextInput value={phone} onChangeText={(value) => setPhone(formatPhone(value))} placeholder="98765 43210" placeholderTextColor={colors.outline} keyboardType="phone-pad" maxLength={11} style={styles.phoneInput} /></View><Text style={styles.assurance}>🔒 Your contact remains strictly within the Sangh directory</Text><PrimaryButton label="Receive Verification Code" disabled={!valid} onPress={() => onContinue(phone.replace(/\s/g, ''))} /></View><View style={styles.trust}><Text style={styles.trustTitle}>Authorized Tirth Portal</Text><Text style={styles.trustCopy}>Connected with Digambar & Shwetambar Trusts</Text></View><Text style={styles.help}>Having trouble accessing?{`\n`}Contact your Sangh Coordinator</Text></KeyboardAvoidingView></Screen>;
}
const styles = StyleSheet.create({ content: { flex: 1 }, header: { alignItems: 'center', marginTop: 20, marginBottom: 34 }, aura: { position: 'absolute', width: 135, height: 135, borderRadius: 68, backgroundColor: colors.goldLight, opacity: .4, top: -20 }, eyebrow: { color: colors.gold, letterSpacing: 1.4, fontSize: 10, fontWeight: '700', marginTop: 18 }, title: { color: colors.maroon, fontFamily: 'serif', fontSize: 31, fontWeight: '600', marginTop: 6 }, copy: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 8, paddingHorizontal: 26 }, label: { color: colors.ink, fontSize: 12, fontWeight: '700', letterSpacing: .4, marginBottom: 7 }, phoneRow: { flexDirection: 'row', alignItems: 'center', height: 52, backgroundColor: colors.white, borderRadius: 12, paddingLeft: 14, marginBottom: 8 }, prefix: { color: colors.maroon, fontWeight: '700', marginRight: 9 }, phoneInput: { flex: 1, height: '100%', color: colors.ink, fontSize: 16, fontWeight: '600', letterSpacing: 1.8, textAlign: 'center', paddingHorizontal: 0, paddingRight: 14 }, assurance: { color: colors.muted, fontSize: 11, marginBottom: 24 }, trust: { marginTop: 32, backgroundColor: colors.surfaceLow, borderRadius: 13, padding: 16 }, trustTitle: { color: colors.ink, fontWeight: '700', fontSize: 13 }, trustCopy: { color: colors.muted, fontSize: 11, marginTop: 4 }, help: { color: colors.outline, textAlign: 'center', lineHeight: 19, fontSize: 12, marginTop: 'auto', paddingTop: 28 } });
