import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { BackButton, Field, PrimaryButton, Screen } from '../components/ui';
import { colors } from '../theme/theme';
import { SignUpDraft } from '../types/navigation';

const phoneFormat = (value: string) => { const digits = value.replace(/\D/g, '').slice(0, 10); return digits.length > 5 ? `${digits.slice(0, 5)} ${digits.slice(5)}` : digits; };
export function SignUpScreen({ onBack, onSubmit }: { onBack: () => void; onSubmit: (draft: SignUpDraft) => void }) {
  const [draft, setDraft] = useState<SignUpDraft>({ fullName: '', dateOfBirth: '', sangh: 'Shree Shankheshwar Parshwanath Sangh, Ahmedabad', phone: '' }); const [accepted, setAccepted] = useState(false);
  const set = (key: keyof SignUpDraft, value: string) => setDraft((old) => ({ ...old, [key]: value }));
  const submit = () => { if (!draft.fullName.trim() || draft.phone.replace(/\s/g, '').length !== 10 || !accepted) return Alert.alert('Complete your details', 'Enter your name, a valid 10-digit mobile number, and accept the community charter.'); onSubmit({ ...draft, phone: draft.phone.replace(/\s/g, '') }); };
  return <Screen scroll><BackButton onPress={onBack} /><View style={styles.header}><Text style={styles.eyebrow}>✦  SANGH REGISTRATION</Text><Text style={styles.title}>Create your account</Text><Text style={styles.copy}>Join your spiritual community and stay connected with your local Sangh.</Text></View><Field label="Full Name" value={draft.fullName} onChangeText={(value) => set('fullName', value)} placeholder="e.g., Jinendra Kumar Shah" autoCapitalize="words" /><Field label="Date of Birth" value={draft.dateOfBirth} onChangeText={(value) => set('dateOfBirth', value)} placeholder="DD / MM / YYYY" keyboardType="number-pad" /><Field label="Select Sangh" value={draft.sangh} onChangeText={(value) => set('sangh', value)} placeholder="Your local Sangh" /><Field label="Mobile Number (+91)" value={draft.phone} onChangeText={(value) => set('phone', phoneFormat(value))} placeholder="98765 43210" keyboardType="phone-pad" maxLength={11} /><View style={styles.note}><Text style={styles.noteText}>Your verification connects you directly with Sangh alerts, Pratikraman timings, and Tithi notifications.</Text></View><Pressable style={styles.terms} onPress={() => setAccepted(!accepted)}><View style={[styles.checkbox, accepted && styles.checked]}><Text style={styles.check}>{accepted ? '✓' : ''}</Text></View><Text style={styles.termsText}>I agree to the Terms & Conditions and Sangh Community Charter.</Text></Pressable><PrimaryButton label="Submit" onPress={submit} /><View style={styles.member}><Text style={styles.memberText}>Already a member? </Text><Pressable onPress={onBack}><Text style={styles.signIn}>Sign In</Text></Pressable></View></Screen>;
}
const styles = StyleSheet.create({ header: { marginTop: 22, marginBottom: 25 }, eyebrow: { color: colors.gold, fontSize: 10, fontWeight: '700', letterSpacing: 1.2, marginBottom: 8 }, title: { color: colors.maroon, fontSize: 28, fontWeight: '600', fontFamily: 'serif' }, copy: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 7 }, note: { backgroundColor: colors.surfaceLow, padding: 13, borderRadius: 12, marginBottom: 16 }, noteText: { color: colors.muted, fontSize: 12, lineHeight: 18 }, terms: { flexDirection: 'row', gap: 10, alignItems: 'flex-start', marginBottom: 22 }, checkbox: { width: 20, height: 20, borderRadius: 6, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: colors.maroon }, check: { color: colors.white, fontWeight: '800' }, termsText: { flex: 1, color: colors.muted, fontSize: 12, lineHeight: 18 }, member: { flexDirection: 'row', justifyContent: 'center', marginTop: 17, marginBottom: 18 }, memberText: { color: colors.muted, fontSize: 12 }, signIn: { color: colors.maroon, fontSize: 12, fontWeight: '700' } });
