import { useEffect, useRef } from 'react';
import { Animated, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from '../theme/theme';

export function SplashScreen({ onContinue }: { onContinue: () => void }) {
  const fade = useRef(new Animated.Value(0)).current;
  useEffect(() => { Animated.timing(fade, { toValue: 1, duration: 650, useNativeDriver: true }).start(); }, [fade]);
  return <Pressable style={styles.screen} onPress={onContinue}><Animated.View style={[styles.content, { opacity: fade }]}><View style={styles.top}><Text style={styles.gold}>•</Text><Text style={styles.leaf}>❧</Text><Text style={styles.gold}>•</Text></View><View style={styles.center}><View style={styles.glow} /><Image source={require('../../assets/images/splash-temple.png')} style={styles.templeImage} resizeMode="contain" /><View style={styles.quote}><Text style={styles.sutra}>“Parasparopagraho Jīvānām”</Text><View style={styles.divider}><View style={styles.line} /><Text style={styles.gold}>◆</Text><View style={styles.line} /></View><Text style={styles.meaning}>Souls render service to one another</Text></View></View><View style={styles.bottom}><Text style={styles.tap}>TAP ANYWHERE TO CONTINUE</Text><Text style={styles.diamond}>◆</Text><Text style={styles.wordmark}>J A I N   S A R T H I</Text><Text style={styles.tagline}>DAILY TITHI  •  PACHKHAN  •  DARSHAN</Text></View></Animated.View></Pressable>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.surface }, content: { flex: 1, alignItems: 'center', justifyContent: 'space-between', padding: 30 }, top: { flexDirection: 'row', gap: 10, alignItems: 'center' }, gold: { color: colors.gold, fontSize: 15 }, leaf: { color: colors.gold, fontSize: 21 }, center: { alignItems: 'center', justifyContent: 'center', flex: 1, width: '100%' }, glow: { position: 'absolute', width: 270, height: 270, borderRadius: 135, backgroundColor: colors.goldLight, opacity: .38 }, templeImage: { width: 218, height: 218, zIndex: 1 }, quote: { alignItems: 'center', marginTop: 28 }, sutra: { fontFamily: 'serif', fontSize: 19, fontWeight: '600', fontStyle: 'italic', color: colors.maroon }, divider: { flexDirection: 'row', gap: 7, alignItems: 'center', marginTop: 9 }, line: { width: 29, height: 1, backgroundColor: '#D6AD51' }, meaning: { marginTop: 7, color: colors.muted, fontSize: 12 }, bottom: { alignItems: 'center' }, tap: { color: colors.outline, fontSize: 9, letterSpacing: 1.4, fontWeight: '700', marginBottom: 14 }, diamond: { color: colors.gold, fontSize: 13, marginBottom: 8 }, wordmark: { color: colors.ink, fontSize: 12, letterSpacing: 2, fontWeight: '700' }, tagline: { marginTop: 7, color: colors.outline, fontSize: 9, letterSpacing: .9 } });
